version: 2
updates:
  - package-ecosystem: docker
    directories:
      - /**
    schedule:
      interval: weekly
    groups:
      docker-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directories:
      - /**
    schedule:
      interval: weekly
    groups:
      gha-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: nuget
    cooldown:
      default-days: 3
    directories:
      - /**
    schedule:
      interval: weekly
    groups:
      dotnet-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: pip
    cooldown:
      default-days: 3
      exclude:
        - ixbrl-viewer
    directories:
      - /**
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: cx_Freeze
      - dependency-name: freeze-core
