repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Prevent committing directly to master
      - id: no-commit-to-branch
        args:
          - --branch=master
      # Sorts entries in requirements*.txt
      - id: requirements-txt-fixer
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: ./scripts/run-pre-commit.sh mypy --namespace-packages
        language: script
        types: [python]
        require_serial: true
        files: ^(arelle)/.+\.py$
