version: '3'
services:
  arelle:
    build: .
    command: sh start_arelle.sh
    privileged: true
    devices:
      - "/dev/fuse"
    volumes:
      - .:/opt/arelle
      - ${HOST_PATH}:/index/data
    environment:
      HOST_PATH:
      AWS_REGION:
      AWS_ACCESS_KEY:
      AWS_SECRET_ACCESS_KEY:
