"""
See COPYRIGHT.md for copyright information.
"""
from __future__ import annotations

from arelle.Cntlr import Cntlr
from arelle.ModelValue import QName
from arelle.ValidateXbrl import ValidateXbrl
from arelle.typing import TypeGetText
from arelle.utils.validate.ValidationPlugin import ValidationPlugin
from .PluginValidationDataExtension import PluginValidationDataExtension

import regex as re

_: TypeGetText

DANISH_CURRENCY_ID = "DKK"
NAMESPACE_ARR = "http://xbrl.dcca.dk/arr"
NAMESPACE_CMN = "http://xbrl.dcca.dk/cmn"
NAMESPACE_FSA = "http://xbrl.dcca.dk/fsa"
NAMESPACE_GSD = "http://xbrl.dcca.dk/gsd"
NAMESPACE_SOB = "http://xbrl.dcca.dk/sob"
PERSONNEL_EXPENSE_THRESHOLD = 200000
ROUNDING_MARGIN = 1000
REQUIRED_STATEMENT_OF_CHANGES_IN_EQUITY_FACTS = 3
REQUIRED_DISCLOSURE_OF_EQUITY_FACTS = 2


class ValidationPluginExtension(ValidationPlugin):
    def newPluginData(self, cntlr: Cntlr, validateXbrl: ValidateXbrl | None) -> PluginValidationDataExtension:
        return PluginValidationDataExtension(
            self.name,
            accountingPolicyConceptQns=frozenset([
                QName.fromParts("DescriptionMethodsOfRecognitionAndMeasurementBasisForCashFlowsStatement", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfAccountingPoliciesRelatedToDerivativeFinancialInstruments", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfAnyFailureOfApplyingEliminationBetweenConsolidatedEnterprises", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfChangeInInventoriesOfFinishedGoodsWorkInProgressAndGoodsForResale", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfChangesInCompositionOfEntityActivities", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfEffectOfChangeInAccountingEstimatesOnAssetsLiabilitiesEquityFinancialPositionAndResults", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfEffectOfChangeInRecognitionAndMeasurementBasisOfAssetsAndLiabilitiesAsResultOfErrors", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfEffectOfDerogationFromProvisionsOfDanishFinancialStatementsActOnAssetsLiabilitiesEquityFinancialPositionAndResults", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfGeneralMattersRelatedToRecognitionMeasurementAndChangesInAccountingPolicies", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfImpairmentOfFinancialAssets", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfIncomeFromOtherInvestmentsAndReceivablesThatAreFixedAssets", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfKeyFiguresAndFinancialRatios", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfAmortisationOfNoncurrentAssets", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfAssetsMeantForSale", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfCurrentTaxReceivablesAndLiabilities", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfDividends", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfForeignCurrencies", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfHedgingRecognisedExpectedToReceiveAndAssumedAssetsAndLiabilities", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfImpairmentLossesAndDepreciation", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfIncomeExceedCostAndCostExceedsIncomeForTheFinancialYear", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfInvestments", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfInvestmentsAsCurrentAssets", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfLeases", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfLiquidationAccount", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfPrepayments", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisForDistributions", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisForInvestmentsInJointVentures", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisForInvestmentsInSubsidiariesAndAssociates", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisIncludingBasesUsedForRevaluationsDepreciationAmortisationEstimatedResidualValueUsefulLifeWritedownsUpwardAndDownwardAdjustments", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfAdministrativeExpenses", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfAssetsAndLiabilities", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfCashAndCashEquivalents", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfContractWorkInProgress", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfCostOfProduction", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfCostOfSales", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfDeferredIncomeAssets", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfDeferredIncomeLiabilities", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfDistributionCosts", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfEmployeeBenefitExpense", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfEquity", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfExpensesFromInvestmentsInGroupEnterprisesAndAssociates", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfExternalExpenses", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfFinanceExpenses", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfFinanceIncome", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfFinanceIncomeAndExpenses", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfGainsLossesFromCurrentValueAdjustmentsOfBiologicalAssets", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfGainsLossesFromCurrentValueAdjustmentsOfInvestmentProperty", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfGainsLossesFromCurrentValueAdjustmentsOfOtherInvestmentAssets", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfGrossProfitLoss", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIncomeAndExpensesFromInvestmentsInGroupEnterprisesAndAssociates", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIncomeAndExpensesFromInvestmentsInJointVentures", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIncomeFromInvestmentsInGroupEnterprisesAndAssociates", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIncomeStatementItems", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIndirectCostsOfProductionRecognisedUnderAssets", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfIntangibleAssets", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfInventories", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfInvestmentProperty", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfInvestments", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfLeaseholdImprovements", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfLiabilitiesOtherThanProvisions", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfOtherInvestmentAssets", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfOtherOperatingExpenses", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfOtherOperatingIncome", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfOtherOperatingIncomeAndExpenses", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfOtherProvisions", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfPropertyCosts", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfPropertyPlantAndEquipment", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfProvisions", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfReceivables", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfResearchAndDevelopmentExpendituresRecognisedAsExpenses", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfRevenue", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfSpecialItems", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfTaxExpenses", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisOfTaxPayablesAndDeferredTax", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisUsedAtEstablishment", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfRecognitionAndMeasurementBasisUsedInBusinessCombinations", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfStatingKeyFiguresAndFinancialRatiosIncludedInManagementReview", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfMethodsOfTranslationOfForeignCurrencies", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfOtherKeyFiguresAndFinancialRatios", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfOtherTaxExpenses", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfOwnWorkCapitalised", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfPublicGrants", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfRawMaterialsAndConsumablesUsed", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfRecognitionAndMeasurementBasisForDiscontinuedOperationsBalanceSheet", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfRemainingPositiveOrNegativeBalancesRelatedToAcquisitionAndUnitingOfInterestsAndMethodsUsedInConnectionWithTheirCalculation", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfWritedownsOfCurrentAssetsThatExceedNormalWritedowns", NAMESPACE_FSA),
                QName.fromParts("DisclosureOfAccountingPolicies", NAMESPACE_FSA),
                QName.fromParts("DisclosureOfTrueAndFairViewAndGoingConcern", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfAmortizationPeriodForGoodwill", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfAssumptionsOnWhichChosenCalculationMethodHasBeenBasedForFinancialAssetsAndLiabilitiesMeasuredAtNetPresentValueOrAmortisedCost", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfAssumptionsOnWhichChosenCalculationMethodHasBeenBasedForInvestmentsAndBiologicalAssetsMeasuredAtFairValue", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfBasisOnWhichEquityInvestmentsInSubsidiariesAndAssociatesHaveBeenRecognisedAtCost", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfChangeInAccountingEstimates", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfChangeInRecognitionAndMeasurementBasisOfAssetsAndLiabilitiesAsResultOfErrors", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfDerogationFromProvisionsOfDanishFinancialStatementsActOnAssetsLiabilitiesEquityFinancialPositionAndResults", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfDifferenceInBalanceSheetDatesBetweenParentAndConsolidatedSubsidiariesAndDescriptionOfImportantEventsOccurringAtThatTime", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfDifferenceInMethodsOfRecognitionAndMeasurementBasisBetweenParentAndConsolidatedGroupEnterprise", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfEntitysDefinitionOfCashAndCashEquivalents", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfGroundsOfNoncomparabilityOrRestatement", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfNotDisclosingInformationOnAGroupEntity", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfOtherMethodsOfRecognitionAndMeasurementBasisForAssetsInPreviousPeriod", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfWhetherInterestIsIncludedInCost", NAMESPACE_FSA),
                QName.fromParts("InformationOnChangesAndEffectsOfChangesOnRecognitionAndMeasurementBasisResultingFromChangesInAccountingEstimatesOrErrors", NAMESPACE_FSA),
                QName.fromParts("InformationOnConsolidatedResultsAndEquityIfSubsidiaryHasNotBeenPreviouslyIncludedInConsolidatedFinancialStatementsAndParentHoldsInvestmentsInSubsidiarySolelyWithViewToItsSubsequentTransfer", NAMESPACE_FSA),
                QName.fromParts("InformationOnConsolidations", NAMESPACE_FSA),
                QName.fromParts("InformationOnHedging", NAMESPACE_FSA),
                QName.fromParts("InformationOnIncentivePrograms", NAMESPACE_FSA),
                QName.fromParts("InformationOnIntragroupTransactions", NAMESPACE_FSA),
                QName.fromParts("InformationOnLeasingContracts", NAMESPACE_FSA),
                QName.fromParts("InformationOnMinorityInterests", NAMESPACE_FSA),
                QName.fromParts("InformationOnNoncomparabilityOrRestatement", NAMESPACE_FSA),
                QName.fromParts("InformationOnOmissionOfConsolidatedFinancialStatement", NAMESPACE_FSA),
                QName.fromParts("InformationOnReportingClassOfEntity", NAMESPACE_FSA),
                QName.fromParts("InformationOnSegments", NAMESPACE_FSA),
                QName.fromParts("InformationOnSignificantUncertainties", NAMESPACE_FSA),
                QName.fromParts("InformationOnSpecificPrerequisitesRegardingDevelopmentProjectsAndTaxAssets", NAMESPACE_FSA),
                QName.fromParts("InformationOnSubsequentEvents", NAMESPACE_FSA),
                QName.fromParts("InformationOnSubsidiariesHavingPresentedTheAnnualReportEtcWithReferenceToTheDanishFinancialStatementsAct78aConcerningTheExceptionForReportingClassCMediumsizeSubsidiariesWhichChoosesToPresentTheAnnualReportEtcAccordingToReportingClassB", NAMESPACE_FSA),
                QName.fromParts("InformationOnThePrincipalModificationsAsResultOfTheLiquidation", NAMESPACE_FSA),
                QName.fromParts("InformationOnTimingDifferencesInCustomerPaymentsEspeciallyForUtilities", NAMESPACE_FSA),
                QName.fromParts("InformationOnTreatmentOfAdditionalPaymentsFromAndRepaymentsToRelatedParties", NAMESPACE_FSA),
                QName.fromParts("InformationOnTrueAndFairViewIfProvisionsOfDanishFinancialStatementsActAreNotSufficient", NAMESPACE_FSA),
                QName.fromParts("InformationOnUncertaintiesRelatingToGoingConcern", NAMESPACE_FSA),
                QName.fromParts("SubsidiariesHasPresentedTheAnnualReportEtc.WithReferenceToTheDanishFinancialStatementsAct78aConcerningTheExceptionForReportingClassCMediumsizeSubsidiariesWhichChoosesToPresentTheAnnualReportEtcAccordingToReportingClassB", NAMESPACE_FSA),
            ]),
            addressOfSubmittingEnterprisePostcodeAndTownQn=QName.fromParts("AddressOfSubmittingEnterprisePostcodeAndTown", NAMESPACE_GSD),
            addressOfSubmittingEnterpriseStreetAndNumberQn=QName.fromParts("AddressOfSubmittingEnterpriseStreetAndNumber", NAMESPACE_GSD),
            allReportingPeriodsMemberQn=QName.fromParts("AllReportingPeriodsMember", NAMESPACE_GSD),
            annualReportTypes=frozenset([
                "Årsrapport",
                "årsrapport",
                "Annual report",
                "Likvidationsregnskab",
                "likvidationsregnskab",
                "Liquidation accounts",
            ]),
            assetsQn=QName.fromParts("Assets", NAMESPACE_FSA),
            auditedAssuranceReportsDanish="Andre erklæringer med sikkerhed",
            auditedAssuranceReportsEnglish="The independent auditor's reports (Other assurance Reports)",
            auditedExtendedReviewDanish="Erklæring om udvidet gennemgang",
            auditedExtendedReviewEnglish="Auditor's report on extended review",
            auditedFinancialStatementsDanish="Revisionspåtegning",
            auditedFinancialStatementsEnglish="Auditor's report on audited financial statements",
            auditedNonAssuranceReportsDanish="Andre erklæringer uden sikkerhed",
            auditedNonAssuranceReportsEnglish="Auditor's reports (Other non-assurance reports)",
            averageNumberOfEmployeesQn=QName.fromParts("AverageNumberOfEmployees", NAMESPACE_FSA),
            balanceSheetQnLessThanOrEqualToAssets=frozenset([
                QName.fromParts("NoncurrentAssets", NAMESPACE_FSA),
                QName.fromParts("IntangibleAssets", NAMESPACE_FSA),
                QName.fromParts("CompletedDevelopmentProjects", NAMESPACE_FSA),
                QName.fromParts("ConcessionsOriginatingFromDevelopmentProjects", NAMESPACE_FSA),
                QName.fromParts("PatentsOriginatingFromDevelopmentProjects", NAMESPACE_FSA),
                QName.fromParts("TrademarksOriginatingFromDevelopmentProjects", NAMESPACE_FSA),
                QName.fromParts("OtherSimilarRightsOriginatingFromDevelopmentProjects", NAMESPACE_FSA),
                QName.fromParts("AcquiredIntangibleAssets", NAMESPACE_FSA),
                QName.fromParts("AcquiredConcessions", NAMESPACE_FSA),
                QName.fromParts("AcquiredPatents", NAMESPACE_FSA),
                QName.fromParts("AcquiredLicences", NAMESPACE_FSA),
                QName.fromParts("AcquiredTrademarks", NAMESPACE_FSA),
                QName.fromParts("AcquiredOtherSimilarRights", NAMESPACE_FSA),
                QName.fromParts("Goodwill", NAMESPACE_FSA),
                QName.fromParts("DevelopmentProjectsInProgressAndPrepaymentsForIntangibleAssets", NAMESPACE_FSA),
                QName.fromParts("DevelopmentProjectsInProgress", NAMESPACE_FSA),
                QName.fromParts("PrepaymentsForIntangibleAssets", NAMESPACE_FSA),
                QName.fromParts("PropertyPlantAndEquipment", NAMESPACE_FSA),
                QName.fromParts("LandAndBuildings", NAMESPACE_FSA),
                QName.fromParts("Land", NAMESPACE_FSA),
                QName.fromParts("Buildings", NAMESPACE_FSA),
                QName.fromParts("InvestmentProperty", NAMESPACE_FSA),
                QName.fromParts("OtherInvestmentAssets", NAMESPACE_FSA),
                QName.fromParts("PlantAndMachinery", NAMESPACE_FSA),
                QName.fromParts("FixturesFittingsToolsAndEquipment", NAMESPACE_FSA),
                QName.fromParts("BiologicalAssets", NAMESPACE_FSA),
                QName.fromParts("LeaseholdImprovements", NAMESPACE_FSA),
                QName.fromParts("Ships", NAMESPACE_FSA),
                QName.fromParts("Planes", NAMESPACE_FSA),
                QName.fromParts("RightofuseAssets", NAMESPACE_FSA),
                QName.fromParts("PropertyPlantAndEquipmentInProgressAndPrepaymentsForPropertyPlantAndEquipment", NAMESPACE_FSA),
                QName.fromParts("PropertyPlantAndEquipmentInProgress", NAMESPACE_FSA),
                QName.fromParts("PrepaymentsForPropertyPlantAndEquipment", NAMESPACE_FSA),
                QName.fromParts("LongtermInvestmentsAndReceivables", NAMESPACE_FSA),
                QName.fromParts("LongtermInvestmentsInGroupEnterprises", NAMESPACE_FSA),
                QName.fromParts("LongtermInvestmentsInAssociates", NAMESPACE_FSA),
                QName.fromParts("LongtermParticipatingInterests", NAMESPACE_FSA),
                QName.fromParts("LongtermInvestmentsInJointVentures", NAMESPACE_FSA),
                QName.fromParts("LongtermReceivablesFromGroupEnterprises", NAMESPACE_FSA),
                QName.fromParts("LongtermReceivablesFromAssociates", NAMESPACE_FSA),
                QName.fromParts("LongtermReceivablesFromParticipatingInterests", NAMESPACE_FSA),
                QName.fromParts("LongtermReceivablesFromJointVentures", NAMESPACE_FSA),
                QName.fromParts("OtherLongtermInvestments", NAMESPACE_FSA),
                QName.fromParts("OtherLongtermReceivables", NAMESPACE_FSA),
                QName.fromParts("LongtermReceivablesFromOwnersAndManagement", NAMESPACE_FSA),
                QName.fromParts("NoncurrentDeferredTaxAssets", NAMESPACE_FSA),
                QName.fromParts("DepositsLongtermInvestmentsAndReceivables", NAMESPACE_FSA),
                QName.fromParts("CostExceedsIncomeForTheFinancialYearLongtermReceivables", NAMESPACE_FSA),
                QName.fromParts("ContributedCapitalInArrearsLongTerm", NAMESPACE_FSA),
                QName.fromParts("NoncurrentContractAssets", NAMESPACE_FSA),
                QName.fromParts("CurrentAssets", NAMESPACE_FSA),
                QName.fromParts("Inventories", NAMESPACE_FSA),
                QName.fromParts("RawMaterialsAndConsumables", NAMESPACE_FSA),
                QName.fromParts("WorkInProgress", NAMESPACE_FSA),
                QName.fromParts("ManufacturedGoodsAndGoodsForResale", NAMESPACE_FSA),
                QName.fromParts("PrepaymentsForGoods", NAMESPACE_FSA),
                QName.fromParts("Livestock", NAMESPACE_FSA),
                QName.fromParts("PropertyHeldForSaleInTheOrdinaryCourseOfBusiness", NAMESPACE_FSA),
                QName.fromParts("AssetsHeldForSaleInventories", NAMESPACE_FSA),
                QName.fromParts("ShorttermReceivables", NAMESPACE_FSA),
                QName.fromParts("ShorttermTradeReceivables", NAMESPACE_FSA),
                QName.fromParts("ContractWorkInProgress", NAMESPACE_FSA),
                QName.fromParts("ShorttermReceivablesFromGroupEnterprises", NAMESPACE_FSA),
                QName.fromParts("ShorttermReceivablesFromAssociates", NAMESPACE_FSA),
                QName.fromParts("ShorttermReceivablesFromJointVentures", NAMESPACE_FSA),
                QName.fromParts("ShorttermReceivablesFromParticipatingInterests", NAMESPACE_FSA),
                QName.fromParts("ShorttermReceivablesDividendsFromGroupEnterprises", NAMESPACE_FSA),
                QName.fromParts("ShorttermReceivablesDividendsFromAssociates", NAMESPACE_FSA),
                QName.fromParts("ShorttermReceivablesDividendsFromJointVentures", NAMESPACE_FSA),
                QName.fromParts("ShorttermReceivablesDividendsFromParticipatingInterests", NAMESPACE_FSA),
                QName.fromParts("CurrentDeferredTaxAssets", NAMESPACE_FSA),
                QName.fromParts("ShorttermTaxReceivables", NAMESPACE_FSA),
                QName.fromParts("ShorttermTaxReceivablesFromGroupEnterprises", NAMESPACE_FSA),
                QName.fromParts("VatAndDutiesReceivables", NAMESPACE_FSA),
                QName.fromParts("OtherShorttermReceivables", NAMESPACE_FSA),
                QName.fromParts("ContributedCapitalInArrears", NAMESPACE_FSA),
                QName.fromParts("ShorttermReceivablesFromOwnersAndManagement", NAMESPACE_FSA),
                QName.fromParts("DeferredIncomeAssets", NAMESPACE_FSA),
                QName.fromParts("CostExceedsIncomeForTheFinancialYearShorttermReceivables", NAMESPACE_FSA),
                QName.fromParts("TimingDifferencesShorttermReceivablesEspeciallyUtilities", NAMESPACE_FSA),
                QName.fromParts("CurrentContractAssets", NAMESPACE_FSA),
                QName.fromParts("DerivativeFinancialInstrumentsShorttermAssets", NAMESPACE_FSA),
                QName.fromParts("ShorttermInvestments", NAMESPACE_FSA),
                QName.fromParts("ShorttermInvestmentsInGroupEnterprises", NAMESPACE_FSA),
                QName.fromParts("OtherShorttermInvestments", NAMESPACE_FSA),
                QName.fromParts("CashAndCashEquivalents", NAMESPACE_FSA),
                QName.fromParts("AssetsMeantForSale", NAMESPACE_FSA),
            ]),
            basisForAdverseOpinionDanish="Grundlag for afkræftende konklusion",
            basisForAdverseOpinionEnglish="Basis for Adverse Opinion",
            basisForDisclaimerOpinionDanish="Grundlag for manglende konklusion",
            basisForDisclaimerOpinionEnglish="Basis for Disclaimer of Opinion",
            basisForQualifiedOpinionDanish="Grundlag for konklusion med forbehold",
            basisForQualifiedOpinionEnglish="Basis for Qualified Opinion",
            classOfReportingEntityQn=QName.fromParts("ClassOfReportingEntity", NAMESPACE_FSA),
            cClassOfReportingEntityEnums = frozenset([
                "SelectedElementsFromReportingClassD",
                "Reporting class C, medium-size enterprise",
                "Regnskabsklasse C, stor virksomhed",
                "Reporting class C, large enterprise"]),
            dClassOfReportingEntityEnums = frozenset([
                "Regnskabsklasse D",
                "Reporting class D"
            ]),
            consolidatedMemberQn=QName.fromParts("ConsolidatedMember", NAMESPACE_CMN),
            consolidatedSoloDimensionQn=QName.fromParts("ConsolidatedSoloDimension", NAMESPACE_CMN),
            cpr_regex=re.compile(r"^([0-2][0-9]|3[0-1])(0[1-9]|1[0-2])[0-9]{2}-[0-9]{4}"),
            dateOfApprovalOfAnnualReportQn=QName.fromParts("DateOfApprovalOfAnnualReport", NAMESPACE_SOB),
            dateOfExtraordinaryDividendDistributedAfterEndOfReportingPeriod=QName.fromParts("DateOfExtraordinaryDividendDistributedAfterEndOfReportingPeriod", NAMESPACE_FSA),
            dateOfGeneralMeetingQn=QName.fromParts("DateOfGeneralMeeting", NAMESPACE_GSD),
            declarationObligationQns=frozenset([
                QName.fromParts("ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyTheCriminalCodeAndFiscalTaxAndSubsidyLegislationAudit", NAMESPACE_ARR),
                QName.fromParts("ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyTheCompaniesActOrEquivalentLegislationThatTheCompanyIsSubjectToAudit", NAMESPACE_ARR),
                QName.fromParts("ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyLegislationOnFinancialReportingIncludingAccountingAndStorageOfAccountingRecordsAudit", NAMESPACE_ARR),
                QName.fromParts("ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyOtherMattersAudit", NAMESPACE_ARR),
                ]),
            descriptionOfQualificationsOfAssuranceEngagementPerformedQn=QName.fromParts("DescriptionOfQualificationsOfAssuranceEngagementPerformed", NAMESPACE_ARR),
            descriptionOfQualificationsOfAuditedFinancialStatementsQn=QName.fromParts("DescriptionOfQualificationsOfAuditedFinancialStatements", NAMESPACE_ARR),
            descriptionOfQualificationsOfFinancialStatementsExtendedReviewQn=QName.fromParts("DescriptionOfQualificationsOfFinancialStatementsExtendedReview", NAMESPACE_ARR),
            descriptionsOfQualificationsOfReviewedFinancialStatementsQn=QName.fromParts("DescriptionsOfQualificationsOfReviewedFinancialStatements", NAMESPACE_ARR),
            disclosureOfEquityQns=frozenset([
                QName.fromParts("InformationOnClassesOfIssuedShares", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfClassOfIssuedShares", NAMESPACE_FSA),
                QName.fromParts("NumberOfIssuedShares", NAMESPACE_FSA),
                QName.fromParts("NominelValuePerUnitShare", NAMESPACE_FSA),
                QName.fromParts("AccountingParValuePerUnitShare", NAMESPACE_FSA),
                QName.fromParts("NominalValueOfIssuedShares", NAMESPACE_FSA),
                QName.fromParts("InformationOnExpensesIncurredInFormationOfEntityOrIncreaseInShareCapital", NAMESPACE_FSA),
                QName.fromParts("ExpensesIncurredInFormationOfEntityOrIncreaseInShareCapital", NAMESPACE_FSA),
                QName.fromParts("RetrospectiveInformationOnContributedCapital", NAMESPACE_FSA),
                QName.fromParts("IncreaseDecreaseOfCapital", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfTreasurySharesHold", NAMESPACE_FSA),
                QName.fromParts("NumberOfTreasurySharesHold", NAMESPACE_FSA),
                QName.fromParts("NominalValueOfTreasurySharesHold", NAMESPACE_FSA),
                QName.fromParts("AccountingParValueOfTreasurySharesHold", NAMESPACE_FSA),
                QName.fromParts("PercentageOfContributedCapitalOfTreasurySharesHold", NAMESPACE_FSA),
                QName.fromParts("InformationOnTreasurySharesAcquired", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfTreasurySharesAcquired", NAMESPACE_FSA),
                QName.fromParts("NumberOfTreasurySharesAcquired", NAMESPACE_FSA),
                QName.fromParts("NominalValueOfTreasurySharesAcquired", NAMESPACE_FSA),
                QName.fromParts("AccountingParValueOfTreasurySharesAcquired", NAMESPACE_FSA),
                QName.fromParts("PercentageOfContributedCapitalOfTreasurySharesAcquired", NAMESPACE_FSA),
                QName.fromParts("PurchasePriceOfTreasurySharesAcquired", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfReasonForAcquisitionOfTreasuryShares", NAMESPACE_FSA),
                QName.fromParts("InformationOnTreasurySharesSold", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfTreasurySharesSold", NAMESPACE_FSA),
                QName.fromParts("NumberOfTreasurySharesSold", NAMESPACE_FSA),
                QName.fromParts("NominalValueOfTreasurySharesSold", NAMESPACE_FSA),
                QName.fromParts("PercentageOfContributedCapitalOfTreasurySharesSold", NAMESPACE_FSA),
                QName.fromParts("SalesPriceOfTreasurySharesSold", NAMESPACE_FSA),
                QName.fromParts("InformationOnTreasurySharesAcquiredAsSecurity", NAMESPACE_FSA),
                QName.fromParts("DescriptionOfTreasurySharesAcquiredAsSecurity", NAMESPACE_FSA),
                QName.fromParts("NumberOfTreasurySharesAcquiredAsSecurity", NAMESPACE_FSA),
                QName.fromParts("NominalValueOfTreasurySharesAcquiredAsSecurity", NAMESPACE_FSA),
                QName.fromParts("AccountingParValueOfTreasurySharesAcquiredAsSecurity", NAMESPACE_FSA),
                QName.fromParts("PercentageOfContributedCapitalOfTreasurySharesAcquiredAsSecurity", NAMESPACE_FSA),
                QName.fromParts("PurchasePriceOfTreasurySharesAcquiredAsSecurity", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfReasonForAcquisitionOfTreasurySharesAsSecurity", NAMESPACE_FSA),
                QName.fromParts("ExplanationOfChangeInMinorityInterestsProportionateShareOfSubsidiariesEquity", NAMESPACE_FSA),
                QName.fromParts("DisclosureOfDistributions", NAMESPACE_FSA),
                QName.fromParts("Distributions", NAMESPACE_FSA),
                QName.fromParts("DisclosureOfHedgeFund", NAMESPACE_FSA),
                QName.fromParts("HedgeFund", NAMESPACE_FSA),
                QName.fromParts("DisclosureOfReserveFund", NAMESPACE_FSA),
                QName.fromParts("ReserveFund", NAMESPACE_FSA),
                QName.fromParts("DisclosureOfReservesAvailable", NAMESPACE_FSA),
                QName.fromParts("TransferredToFromReservesAvailable", NAMESPACE_FSA),
                QName.fromParts("DisclosureOfLiquidationAccount", NAMESPACE_FSA),
                QName.fromParts("LiquidationAccount", NAMESPACE_FSA),
                QName.fromParts("InformationOnReserveForEntrepreneurialCompany", NAMESPACE_FSA),
                QName.fromParts("ReserveForEntrepreneurialCompany", NAMESPACE_FSA),
                QName.fromParts("InformationOnChangesAsResultOfApplicationOfUnitingOfInterestsMethod", NAMESPACE_FSA),
                QName.fromParts("IncreaseDecreaseOfReservesThroughApplicationOfUnitingOfInterestsMethodEquity", NAMESPACE_FSA),
                QName.fromParts("DisclosureOfRevaluationReserve", NAMESPACE_FSA),
                QName.fromParts("RevaluationReserve", NAMESPACE_FSA),
                QName.fromParts("AdditionsToRevaluationReserveInReportingPeriod", NAMESPACE_FSA),
                QName.fromParts("ReversalsOfPriorYearsRevaluationsOfRevaluationReserve", NAMESPACE_FSA),
                QName.fromParts("AmortisationOfRevaluationReserveInReportingPeriod", NAMESPACE_FSA),
                QName.fromParts("DisposalsOfRevaluationReserveInReportingPeriod", NAMESPACE_FSA),
                QName.fromParts("RecognitionAndMeasurementOfTheTaxEffectOfTheMovementsInTheRevaluationReserve", NAMESPACE_FSA),
                QName.fromParts("CurrentValueReserve", NAMESPACE_FSA),
                QName.fromParts("AdjustmentsOfCurrentValueReserveGainsLoss", NAMESPACE_FSA),
                QName.fromParts("CurrentValueReserveRealized", NAMESPACE_FSA),
                QName.fromParts("CurrentValueReserveReversed", NAMESPACE_FSA),
            ]),
                distributionOfResultsQns=frozenset([
                QName.fromParts("DistributionsResultDistribution", NAMESPACE_FSA),
                QName.fromParts("ExtraordinaryDistributions", NAMESPACE_FSA),
                QName.fromParts("ProposedDividendRecognisedInEquity", NAMESPACE_FSA),
                QName.fromParts("ProposedExtraordinaryDividendRecognisedInEquity", NAMESPACE_FSA),
                QName.fromParts("ProposedExtraordinaryDividendRecognisedInLiabilities", NAMESPACE_FSA),
                QName.fromParts("TransferredFromToHedgeFund", NAMESPACE_FSA),
                QName.fromParts("TransferredFromToReserveFund", NAMESPACE_FSA),
                QName.fromParts("TransferredFromToReservesAvailable", NAMESPACE_FSA),
                QName.fromParts("TransferredToFromEquityAttributableToParent", NAMESPACE_FSA),
                QName.fromParts("TransferredToFromMinorityInterests", NAMESPACE_FSA),
                QName.fromParts("TransferredToFromOtherStatutoryReserves", NAMESPACE_FSA),
                QName.fromParts("TransferredToFromReserveAccordingToArticlesOfAssociation", NAMESPACE_FSA),
                QName.fromParts("TransferredToFromReserveForNetRevaluationAccordingToEquityMethod", NAMESPACE_FSA),
                QName.fromParts("TransferredToFromReserveForNetRevaluationOfInvestmentAssets", NAMESPACE_FSA),
                QName.fromParts("TransferredToFromRestOfOtherReserves", NAMESPACE_FSA),
                QName.fromParts("TransferredToFromRetainedEarnings", NAMESPACE_FSA),
                QName.fromParts("TransferredToReserveForCurrentValueAdjustmentsOfCurrencyGains", NAMESPACE_FSA),
                QName.fromParts("TransferredToReserveForCurrentValueOfHedging", NAMESPACE_FSA),
                QName.fromParts("TransferredToReserveForDevelopmentExpenditure", NAMESPACE_FSA),
                QName.fromParts("TransferredToReserveForEntrepreneurialCompany", NAMESPACE_FSA),
            ]),
            endDateForUseOfDigitalNonregisteredBookkeepingSystemQn=QName.fromParts("EndDateForUseOfDigitalNonregisteredBookkeepingSystem", NAMESPACE_GSD),
            endDateForUseOfDigitalStandardBookkeepingSystemQn=QName.fromParts("EndDateForUseOfDigitalStandardBookkeepingSystem", NAMESPACE_GSD),
            employeeBenefitsExpenseQn=QName.fromParts("EmployeeBenefitsExpense", NAMESPACE_FSA),
            equityQn=QName.fromParts("Equity", NAMESPACE_FSA),
            extraordinaryCostsQn=QName.fromParts("ExtraordinaryCosts", NAMESPACE_FSA),
            extraordinaryIncomeQn=QName.fromParts("ExtraordinaryIncome", NAMESPACE_FSA),
            extraordinaryResultBeforeTaxQn=QName.fromParts("ExtraordinaryResultBeforeTax", NAMESPACE_FSA),
            fr37RestrictedText="has not given rise to reservations",
            forbiddenTypeOfSubmittedReportEnumerations=frozenset([
                "Selskabsselvangivelse",
                "Erklæring om undtagelse fra aflæggelse årsrapport",
                "ESG-rapport",
                "ESG report",
                ]),
            hasNotGivenRiseToReservationsText=frozenset([
                "har ikke givet anledning til forbehold",
                "has not given rise to reservations",
            ]),
            identificationNumberCvrOfAuditFirmQn=QName.fromParts("IdentificationNumberCvrOfAuditFirm", NAMESPACE_CMN),
            identificationNumberCvrOfReportingEntityQn=QName.fromParts("IdentificationNumberCvrOfReportingEntity", NAMESPACE_GSD),
            independentAuditorsReportDanish="Den uafhængige revisors erklæring",
            independentAuditorsReportEnglish="Independent Auditor’s Report",
            independentAuditorsReportReviewDanish="Den uafhængige revisors erklæringer (review)",
            independentAuditorsReportReviewEnglish="The independent auditor’s reports (Review)",
            independentPractitionersExtendedReviewReportDanish="Den uafhængige revisors erklæring om udvidet gennemgang",
            independentPractitionersExtendedReviewReportEnglish="Independent Practitioner’s Extended Review Report",
            independentPractitionersReviewReportDanish="Den uafhængige revisors reviewerklæring",
            independentPractitionersReviewReportEnglish="Independent Practitioner’s Review Report",
            informationOnTypeOfSubmittedReportQn=QName.fromParts("InformationOnTypeOfSubmittedReport", NAMESPACE_GSD),
            legalEntityIdentifierOfReportingEntityQn=QName.fromParts("LegalEntityIdentifierOfReportingEntity", NAMESPACE_GSD),
            liabilitiesQn=QName.fromParts("LiabilitiesAndEquity", NAMESPACE_FSA),
            liabilitiesAndEquityQn=QName.fromParts("LiabilitiesAndEquity", NAMESPACE_FSA),
            liabilitiesOtherThanProvisionsQn=QName.fromParts("LiabilitiesOtherThanProvisions", NAMESPACE_FSA),
            longtermLiabilitiesOtherThanProvisionsQn=QName.fromParts("LongtermLiabilitiesOtherThanProvisions", NAMESPACE_FSA),
            managementEndorsementQns=frozenset([
                QName.fromParts("StatementByExecutiveAndSupervisoryBoards", NAMESPACE_SOB),
                QName.fromParts("TheReportingEntityAppliesTheExceptionConcerningOptingOutOfTheStatementByManagementEtc", NAMESPACE_SOB),
                QName.fromParts("IdentificationOfApprovedAnnualReport", NAMESPACE_SOB),
                QName.fromParts("ConfirmationThatAnnualReportIsPresentedInAccordanceWithRequirementsProvidedForByLegislationAnyStandardsAndRequirementsProvidedByArticlesOfAssociationOrByAgreement", NAMESPACE_SOB),
                QName.fromParts("ConfirmationThatFinancialStatementGivesTrueAndFairViewOfAssetsLiabilitiesEquityFinancialPositionAndResults", NAMESPACE_SOB),
                QName.fromParts("ConfirmationThatSupplementaryReportsGiveTrueAndFairViewInAccordanceWithGenerallyAcceptedGuidelinesForSuchReports", NAMESPACE_SOB),
                QName.fromParts("ManagementsStatementAboutManagementsReview", NAMESPACE_SOB),
                QName.fromParts("RecommendationForApprovalOfAnnualReportByGeneralMeeting", NAMESPACE_SOB),
                QName.fromParts("DateOfApprovalOfAnnualReport", NAMESPACE_SOB),
                QName.fromParts("PlaceOfSignatureOfStatement", NAMESPACE_SOB),
                QName.fromParts("NameAndSurnameOfMemberOfExecutiveBoard", NAMESPACE_CMN),
                QName.fromParts("TitleOfMemberOfExecutiveBoard", NAMESPACE_CMN),
                QName.fromParts("DescriptionOfMemberOfExecutiveBoard", NAMESPACE_CMN),
                QName.fromParts("DescriptionOfObjectionsOfMemberOfExecutiveBoardOnAnnualReport", NAMESPACE_SOB),
                QName.fromParts("DescriptionOfSpecificAndAdequateGroundsForObjectionsOfMemberOfExecutiveBoardOnAnnualReport", NAMESPACE_SOB),
                QName.fromParts("NameAndSurnameOfMemberOfSupervisoryBoard", NAMESPACE_CMN),
                QName.fromParts("TitleOfMemberOfSupervisoryBoard", NAMESPACE_CMN),
                QName.fromParts("DescriptionOfMemberOfSupervisoryBoard", NAMESPACE_CMN),
                QName.fromParts("DescriptionOfObjectionsOfMemberOfSupervisoryBoardOnAnnualReport", NAMESPACE_SOB),
                QName.fromParts("DescriptionOfSpecificAndAdequateGroundsForObjectionsOfMemberOfSupervisoryBoardOnAnnualReport", NAMESPACE_SOB),
                QName.fromParts("IdentificationNumberCVRofParticipantNotPartOfTheRegisteredManagementMemberOfSupervisoryBoard", NAMESPACE_SOB),
                QName.fromParts("NameOfEntityParticipantNotPartOfTheRegisteredManagementMemberOfSupervisoryBoard", NAMESPACE_SOB),
                QName.fromParts("DescriptionOfParticipantNotPartOfTheRegisteredManagementMemberOfSupervisoryBoard", NAMESPACE_SOB),
                QName.fromParts("NameAndSurnameOfMemberOfSupervisoryCommittee", NAMESPACE_GSD),
                QName.fromParts("TitleOfMemberOfSupervisoryCommittee", NAMESPACE_GSD),
                QName.fromParts("DescriptionOfMemberOfSupervisoryCommittee", NAMESPACE_GSD),
                QName.fromParts("NameAndSurnameOfMemberOfSupervisoryCommittee", NAMESPACE_GSD),
                QName.fromParts("TitleOfMemberOfSupervisoryCommittee", NAMESPACE_GSD),
                QName.fromParts("NameAndSurnameOfLiquidator", NAMESPACE_CMN),
                QName.fromParts("TitleOfLiquidator", NAMESPACE_CMN),
                QName.fromParts("DescriptionOfLikvidator", NAMESPACE_CMN),
                QName.fromParts("DescriptionOfObjectionsOfLiquidatorOnAnnualReport", NAMESPACE_SOB),
                QName.fromParts("DescriptionOfSpecificAndAdequateGroundsForObjectionsOfLiquidatorOnAnnualReport", NAMESPACE_SOB),
            ]),
            noncurrentAssetsQn=QName.fromParts("NoncurrentAssets", NAMESPACE_FSA),
            nameAndSurnameOfChairmanOfGeneralMeetingQn=QName.fromParts("NameAndSurnameOfChairmanOfGeneralMeeting", NAMESPACE_GSD),
            nameOfAuditFirmQn=QName.fromParts("NameOfAuditFirm", NAMESPACE_CMN),
            nameOfReportingEntityQn=QName.fromParts("NameOfReportingEntity", NAMESPACE_GSD),
            nameOfSubmittingEnterpriseQn=QName.fromParts("NameOfSubmittingEnterprise", NAMESPACE_GSD),
            otherEmployeeExpenseQn=QName.fromParts("OtherEmployeeExpense", NAMESPACE_FSA),
            otherRenderingOfReportedValueMemberQn=QName.fromParts("OtherRenderingOfReportedValueMember", NAMESPACE_CMN),
            positiveProfitThreshold=1000,
            postemploymentBenefitExpenseQn=QName.fromParts("PostemploymentBenefitExpense", NAMESPACE_FSA),
            precedingReportingPeriodEndDateQn=QName.fromParts("PredingReportingPeriodEndDate", NAMESPACE_GSD),  # Typo in taxonomy
            precedingReportingPeriodStartDateQn=QName.fromParts("PrecedingReportingPeriodStartDate", NAMESPACE_GSD),
            profitLossQn=QName.fromParts("ProfitLoss", NAMESPACE_FSA),
            proposedDividendRecognisedInEquityQn=QName.fromParts("ProposedDividendRecognisedInEquity", NAMESPACE_FSA),
            proposedExtraordinaryDividendRecognisedInLiabilitiesQn=QName.fromParts("ProposedExtraordinaryDividendRecognisedInLiabilities", NAMESPACE_FSA),
            provisionsQn=QName.fromParts("Provisions", NAMESPACE_FSA),
            registrationNumberOfTheDigitalStandardBookkeepingSystemUsedQn=QName.fromParts("RegistrationNumberOfTheDigitalStandardBookkeepingSystemUsed", NAMESPACE_GSD),
            registeredReportingPeriodDeviatingFromReportedReportingPeriodDueArbitraryDatesMemberQn=QName.fromParts("RegisteredReportingPeriodDeviatingFromReportedReportingPeriodDueArbitraryDatesMember", NAMESPACE_GSD),
            reportedValueOtherRenderingOfReportedValueDimensionQn=QName.fromParts("ReportedValueOtherRenderingOfReportedValueDimension", NAMESPACE_CMN),
            reportingClassCLargeDanish="Regnskabsklasse C, stor virksomhed",
            reportingClassCLargeEnglish="Reporting class C, large enterprise",
            reportingClassCLargeLowercaseDanish="regnskabsklasse C, stor virksomhed",
            reportingClassCLargeLowercaseEnglish="reporting class C, large enterprise",
            reportingClassCMediumDanish="Regnskabsklasse C, mellemstor virksomhed",
            reportingClassCMediumEnglish="Reporting class C, medium-size enterprise",
            reportingClassCMediumLowercaseDanish="regnskabsklasse C, mellemstor virksomhed",
            reportingClassCMediumLowercaseEnglish="reporting class C, medium-size enterprise",
            reportingClassDDanish="Regnskabsklasse D",
            reportingClassDEnglish="Reporting class D",
            reportingClassDLowercaseDanish="regnskabsklasse D",
            reportingClassDLowercaseEnglish="reporting class D",
            reportingPeriodEndDateQn=QName.fromParts("ReportingPeriodEndDate", NAMESPACE_GSD),
            reportingPeriodStartDateQn=QName.fromParts("ReportingPeriodStartDate", NAMESPACE_GSD),
            reportingResponsibilitiesOnApprovedAuditorsReportAuditQn=QName.fromParts("ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsAudit", NAMESPACE_ARR),
            reportingResponsibilitiesOnApprovedAuditorsReportsExtendedReviewQn=QName.fromParts("ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsExtendedReview", NAMESPACE_ARR),
            reportingObligationQns = frozenset([
                QName.fromParts("ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyTheCriminalCodeAndFiscalTaxAndSubsidyLegislationExtendedReview", NAMESPACE_ARR),
                QName.fromParts("ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyTheCompaniesActOrEquivalentLegislationThatTheCompanyIsSubjectToExtendedReview", NAMESPACE_ARR),
                QName.fromParts("ReportingResponsibilitiesAccordingToTheDanishExecutiveOrderOnApprovedAuditorsReportsEspeciallyLegislationOnFinancialReportingInApplication", NAMESPACE_ARR),
            ]),
            schemaRefUri="http://archprod.service.eogs.dk/taxonomy/",
            selectedElementsFromReportingClassCQn=QName.fromParts("SelectedElementsFromReportingClassC", NAMESPACE_FSA),
            selectedElementsFromReportingClassDQn=QName.fromParts("SelectedElementsFromReportingClassD", NAMESPACE_FSA),
            shorttermLiabilitiesOtherThanProvisionsQn=QName.fromParts("ShorttermLiabilitiesOtherThanProvisions", NAMESPACE_FSA),
            signatureOfAuditorsDateQn=QName.fromParts("SignatureOfAuditorsDate", NAMESPACE_ARR),
            soloMemberQn=QName.fromParts("SoloMember", NAMESPACE_CMN),
            startDateForUseOfDigitalNonregisteredBookkeepingSystemQn=QName.fromParts("StartDateForUseOfDigitalNonregisteredBookkeepingSystem", NAMESPACE_GSD),
            startDateForUseOfDigitalStandardBookkeepingSystemQn=QName.fromParts("StartDateForUseOfDigitalStandardBookkeepingSystem", NAMESPACE_GSD),
            statementOfChangesInEquityQns=frozenset([
                QName.fromParts("Equity", NAMESPACE_FSA),
                QName.fromParts("IncreaseDecreaseOfEquityThroughCorrectionsOfErrors", NAMESPACE_FSA),
                QName.fromParts("IncreaseDecreaseOfEquityThroughChangesInAccountingPolicies", NAMESPACE_FSA),
                QName.fromParts("AdditionsToDisposalsOfEquityThroughMergersAndBusinessCombinations", NAMESPACE_FSA),
                QName.fromParts("IncreaseDecreaseOfEquityByDivisionAndSaleOfOtherCompany", NAMESPACE_FSA),
                QName.fromParts("IncreaseOfCapital", NAMESPACE_FSA),
                QName.fromParts("IncreaseOfCapitalByConversionOfDebt", NAMESPACE_FSA),
                QName.fromParts("DecreaseOfCapital", NAMESPACE_FSA),
                QName.fromParts("DecreaseOfCapitalDueToDeficitCoverage", NAMESPACE_FSA),
                QName.fromParts("BonusShares", NAMESPACE_FSA),
                QName.fromParts("CostRelatedToIncreaseOfCapital", NAMESPACE_FSA),
                QName.fromParts("PurchaseOfTreasuryShares", NAMESPACE_FSA),
                QName.fromParts("SalesOfTreasuryShares", NAMESPACE_FSA),
                QName.fromParts("PurchaseOfMinorityShares", NAMESPACE_FSA),
                QName.fromParts("SaleOfMinorityShares", NAMESPACE_FSA),
                QName.fromParts("Dividend", NAMESPACE_FSA),
                QName.fromParts("DividendPaid", NAMESPACE_FSA),
                QName.fromParts("DistributionsStatementOfChangesInEquity", NAMESPACE_FSA),
                QName.fromParts("ExtraordinaryDistributionsStatementOfChangesInEquity", NAMESPACE_FSA),
                QName.fromParts("IncreaseDecreaseOfInvestmentsThroughNetExchangeDifferencesEquity", NAMESPACE_FSA),
                QName.fromParts("ValueAdjustmentsOfEquity", NAMESPACE_FSA),
                QName.fromParts("AdjustmentsOfHedgingInstruments", NAMESPACE_FSA),
                QName.fromParts("OtherAdjustmentsOfEquity", NAMESPACE_FSA),
                QName.fromParts("EquityTransfersToReserves", NAMESPACE_FSA),
                QName.fromParts("ProfitLoss", NAMESPACE_FSA),
                QName.fromParts("ChangesInEquityOfTax", NAMESPACE_FSA),
                QName.fromParts("ExtraordinaryDividendPaid", NAMESPACE_FSA),
                QName.fromParts("DividendsFromTreasuryShares", NAMESPACE_FSA),
                QName.fromParts("ReceivablesShareCapitalPaid", NAMESPACE_FSA),
                QName.fromParts("Revaluations", NAMESPACE_FSA),
                QName.fromParts("DepreciationOfEquity", NAMESPACE_FSA),
                QName.fromParts("RevaluationsOfActuarialProfitLossForReportingPeriod", NAMESPACE_FSA),
                QName.fromParts("ImpairmentLossesAndDepreciationOfActuarialGainsLossesStatementOfChangesInEquity", NAMESPACE_FSA),
                QName.fromParts("DissolutionOfPreviousYearsRevaluations", NAMESPACE_FSA),
                QName.fromParts("DissolutionOfFairValueReserve", NAMESPACE_FSA),
                QName.fromParts("DissolutionOfReserves", NAMESPACE_FSA),
                QName.fromParts("AdjustmentsOfHedgingInstrumentsAtFairValue", NAMESPACE_FSA),
                QName.fromParts("AdjustmentsOfCollateralsBySaleOfInvestments", NAMESPACE_FSA),
                QName.fromParts("TransferredFromSharePremium", NAMESPACE_FSA),
                QName.fromParts("TransferToCoverageOfLosses", NAMESPACE_FSA),
                QName.fromParts("ProfitLlossFromGroupEnterprises", NAMESPACE_FSA),
                QName.fromParts("ProfitLossFromAssociates", NAMESPACE_FSA),
                QName.fromParts("ProfitLossFromParticipatingInterests", NAMESPACE_FSA),
                QName.fromParts("ReversedRevaluationsDuringReportingPeriod", NAMESPACE_FSA),
                QName.fromParts("DistributedDividendsFromGroupEnterprises", NAMESPACE_FSA),
                QName.fromParts("DistributedDividendsFromAssociates", NAMESPACE_FSA),
                QName.fromParts("DistributedDividendsFromParticipatingInterests", NAMESPACE_FSA),
                QName.fromParts("CashPaymentsConcerningFormationOfEntity", NAMESPACE_FSA),
                QName.fromParts("ContributionFromGroup", NAMESPACE_FSA),
                QName.fromParts("IncreaseDecreaseOfReservesThroughApplicationOfUnitingOfInterestsMethodEquity", NAMESPACE_FSA)
                ]),
            taxExpenseOnOrdinaryActivitiesQn=QName.fromParts("TaxExpenseOnOrdinaryActivities", NAMESPACE_FSA),
            taxExpenseQn=QName.fromParts("TaxExpense", NAMESPACE_FSA),
            typeOfAuditorAssistanceQn=QName.fromParts("TypeOfAuditorAssistance", NAMESPACE_CMN),
            typeOfBasisForModifiedOpinionOnFinancialStatementsReviewQn=QName.fromParts("TypeOfBasisForModifiedOpinionOnFinancialStatementsReview", NAMESPACE_ARR),
            typeOfDigitalNonregisteredBookkeepingSystemQn=QName.fromParts("TypeOfDigitalNonregisteredBookkeepingSystem", NAMESPACE_GSD),
            typeOfReportingPeriodDimensionQn=QName.fromParts("TypeOfReportingPeriodDimension", NAMESPACE_GSD),
            wagesAndSalariesQn=QName.fromParts("WagesAndSalaries", NAMESPACE_FSA),
        )
