name: 'Merge'
description: 'Fetches and merges a specific SHA from a fork or branch'
inputs:
  commit_sha:
    description: 'The specific commit SHA to merge'
    required: true
  repository_full_name:
    description: 'The full name of the repository to fetch from (e.g., owner/repo)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch Remote SHA
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        
        echo "Fetching from ${{ inputs.repository_full_name }}..."
        git fetch https://github.com/${{ inputs.repository_full_name }}.git ${{ inputs.commit_sha }}

    - name: Merge
      shell: bash
      run: |
        echo "Merging SHA ${{ inputs.commit_sha }}..."
        git merge FETCH_HEAD || {
          echo "::error::Merge conflict detected."
          exit 1
        }
