services:
  ixbrl-viewer-webserver:
    extends:
      file: docker-compose.slim.yml
      service: slim-webserver
    container_name: arelle-ixbrl-viewer-webserver
    build:
      args:
        INCLUDE_IXBRL_VIEWER: "true"
        EXTRA_PIP: "-r requirements-plugins.txt"
        # or
        # EXTRA_PIP: "gunicorn -r requirements-plugins.txt"
