services:
  arelle:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: /start
    ports:
      - 8080:8080
    healthcheck:
      test: /healthcheck
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

