services:
  webserver:
    extends:
      file: docker-compose.slim.yml
      service: slim-webserver
    container_name: arelle-webserver
    build:
      args:
        INCLUDE_EDGAR: "true"
        EXTRA_PIP: "-r requirements-plugins.txt"
