"""
Tests that all arelle Python source files contain the required copyright notice.
"""
import fnmatch
import glob
import os

import pytest

COPYRIGHT_NOTICE = "See COPYRIGHT.md for copyright information."

# Glob patterns (supporting **) matched against normalised forward-slash paths.
# Patterns are prefix-free: use ** to match across directory boundaries.
EXCLUDE_PATTERNS: tuple[str, ...] = (
    # Python bytecode cache directories — never contain editable source.
    '**/__pycache__/**',
    # Auto-generated by setuptools-scm; do not modify directly.
    'arelle/_version.py',
    # Third-party plugins commonly copied into a developer's workspace.
    'arelle/plugin/EDGAR/**',
    'arelle/plugin/FERC/**',
    'arelle/plugin/iXBRLViewerPlugin/**',
    'arelle/plugin/semanticHash/**',
    'arelle/plugin/serializer/**',
    'arelle/plugin/SimpleXBRLModel/**',
    'arelle/plugin/xbrlus/**',
    'arelle/plugin/xendr/**',
    'arelle/plugin/Xince/**',
    'arelle/plugin/xodel/**',
    'arelle/plugin/xule/**',
    # Third-party validation rule sets commonly copied into a developer's workspace.
    'arelle/plugin/validate/DQC/**',
    'arelle/plugin/validate/eforms/**',
    'arelle/plugin/validate/ESEF-DQC/**',
    # Third-party libraries bundled verbatim under the plugin/internet package.
    'arelle/plugin/internet/**',
    # Non-Python static resource files.
    'arelle/resources/**',
    # Third-party bottle web framework re-exported for backwards compatibility.
    'arelle/webserver/bottle.py',
    # Third-party Tkinter widgets bundled verbatim.
    'arelle/CntlrWinTooltip.py',    # Michael Lange's ToolTip widget
    'arelle/TkTableWrapper.py',      # Guilherme Polo, BSD licence
    # Third-party archive plugins bundled verbatim.
    'arelle/archive/plugin/sakaCalendar.py',             # Santhosh Thottingal / SMC
    'arelle/archive/plugin/validate/XFsyntax/xf.py',    # auto-generated by TatSu
    # GNU gettext tools included for i18n tooling — not arelle source.
    'msgfmt.py',
    'pygettext.py',
)

# Source roots to scan, as explicit glob patterns. .py and .pyw only — not .pyc/.pyi/.pyx.
SEARCH_PATTERNS: tuple[str, ...] = (
    '*.py',
    '*.pyw',
    'arelle/**/*.py',
    'arelle/**/*.pyw',
)


def _is_excluded(path: str) -> bool:
    return any(fnmatch.fnmatch(path, pattern) for pattern in EXCLUDE_PATTERNS)


def _is_empty(path: str) -> bool:
    """Return True if the file has no non-whitespace content."""
    if os.path.getsize(path) == 0:
        return True
    with open(path, encoding='utf-8', errors='replace') as fh:
        return not fh.read().strip()


PY_FILES = sorted({
    norm
    for pattern in SEARCH_PATTERNS
    for f in glob.glob(pattern, recursive=True)
    if not _is_excluded(norm := f.replace('\\', '/'))
    and not _is_empty(f)
})

TEST_PARAMS = [
    pytest.param(
        filepath,
        id=filepath,
    )
    for filepath in PY_FILES
]


@pytest.mark.fast
@pytest.mark.parametrize('filepath', TEST_PARAMS)
def test_copyright_notice(filepath: str) -> None:
    with open(filepath, encoding='utf-8', errors='replace') as fh:
        content = fh.read(512)
    assert COPYRIGHT_NOTICE in content, (
        f"{filepath!r} is missing the copyright notice.\n"
        f"Add the following near the top of the file:\n"
        f"  {COPYRIGHT_NOTICE!r}"
    )
