services:
  webserver:
    build:
      context: ../..
      dockerfile: ./docker/arelle-EDGAR/Dockerfile
      args:
        INCLUDE_EDGAR: ${INCLUDE_EDGAR:-}
        EDGAR_REF: ${EDGAR_REF:-}
        XULE_REF: ${XULE_REF:-}
    command: /start.sh
    ports:
      - 8080:8080
    healthcheck:
      test: /healthcheck.sh
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
