from pathlib import Path, PurePath

from tests.integration_tests.validation.conformance_suite_config import (
    ConformanceSuiteAssetConfig,
    ConformanceSuiteConfig,
)

_VERSION = "2026-09-10"

config = ConformanceSuiteConfig(
    args=[
        "--validateTableConstraintsSkipLoading",
    ],
    assets=[
        ConformanceSuiteAssetConfig.conformance_suite(
            Path(f"table-constraints-conformance-{_VERSION}.zip"),
            entry_point=Path(f"table-constraints-conformance-{_VERSION}/table-constraints-index.xml"),
        ),
    ],
    expected_additional_testcase_errors={f"table-constraints-conformance-{_VERSION}/{s}": val for s, val in {
        # Invalid xBRL-CSV test cases prevent report construction, triggering arelle:notLoaded.
        "710-tc-metadata-processor/index-tc-metadata-table.xml:V-817c": {
            "arelle:notLoaded": 1,
        },
        "720-tc-report-processor/index-tc-report-table.xml:V-901-mp-null": {
            "arelle:notLoaded": 1,
        },
        "720-tc-report-processor/index-tc-report-table.xml:V-901-tp-null": {
            "arelle:notLoaded": 1,
        },
        # The tc prefix is not bound to the Table Constraints namespace, so there is no
        # metadata to validate when skipping report loading.
        **{
            f"710-tc-metadata-processor/index-tc-metadata-table.xml:{s}": {
                "arelle:notLoaded": 1,
                "arelle:noTableConstraints": 1,
            }
            for s in ("V-809dc", "V-809de", "V-817b")
        },
        # Three xs:duration key fields without durationType are each reported.
        "720-tc-report-processor/index-tc-report-table.xml:V-25": {
            "tcme:illegalKeyField": 2,
        },
        # The header is also out of order.
        "720-tc-report-processor/index-tc-report-table.xml:V-69": {
            "tcre:invalidColumnOrder": 1,
        },
        # paramThree (xs:duration without durationType) also triggers illegalUniqueKeyOrder because it follows
        # constrained column fields keyOne and keyTwo in the unique key fields list.
        "720-tc-report-processor/index-tc-report-table.xml:V-61": {
            "tcme:illegalUniqueKeyOrder": 1,
        },
        # The sort key names the unique key, so equal consecutive rows violate both.
        **{
            f"generated/row-sorting/index-tc-row-sorting.xml:{s}": {
                "tcre:uniqueKeyViolation": 1,
            }
            for s in (
                "V-GEN-rowSort-eq-decimals-numNegOne-0-sk",
                "V-GEN-rowSort-eq-decimals-numOne-0-sk",
                "V-GEN-rowSort-eq-decimals-numOne-1-sk",
                "V-GEN-rowSort-eq-decimals-numOneMillion-0-sk",
                "V-GEN-rowSort-eq-decimals-numZero-0-sk",
                "V-GEN-rowSort-eq-decimals-numZero-1-sk",
                "V-GEN-rowSort-eq-decimals-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_boolean-boolFalse-0-sk",
                "V-GEN-rowSort-eq-xs_boolean-boolTrue-0-sk",
                "V-GEN-rowSort-eq-xs_byte-numNegOne-0-sk",
                "V-GEN-rowSort-eq-xs_byte-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_byte-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_byte-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_byte-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_byte-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_dateTime-january1st2024Midnight-0-sk",
                "V-GEN-rowSort-eq-xs_dateTime-january1st2024Midnight-1-sk",
                "V-GEN-rowSort-eq-xs_dateTime-january2nd2024Midnight-0-sk",
                "V-GEN-rowSort-eq-xs_dateTime-leapDay2024Midnight-0-sk",
                "V-GEN-rowSort-eq-xs_dateTime-march1st2024Midnight-0-sk",
                "V-GEN-rowSort-eq-xs_decimal-numMaxUnsignedLongPlus1DotZero-0-sk",
                "V-GEN-rowSort-eq-xs_decimal-numMinLongMinus1DotZero-0-sk",
                "V-GEN-rowSort-eq-xs_decimal-numNegPiApprox-0-sk",
                "V-GEN-rowSort-eq-xs_decimal-numNegPiApprox-1-sk",
                "V-GEN-rowSort-eq-xs_decimal-numOne1dp-0-sk",
                "V-GEN-rowSort-eq-xs_decimal-numOne1dp-1-sk",
                "V-GEN-rowSort-eq-xs_decimal-numOne1dp-2-sk",
                "V-GEN-rowSort-eq-xs_decimal-numOne1dp-3-sk",
                "V-GEN-rowSort-eq-xs_decimal-numZero1dp-0-sk",
                "V-GEN-rowSort-eq-xs_decimal-numZero1dp-1-sk",
                "V-GEN-rowSort-eq-xs_decimal-numZero1dp-2-sk",
                "V-GEN-rowSort-eq-xs_decimal-numZero1dp-3-sk",
                "V-GEN-rowSort-eq-xs_decimal-numZero1dp-4-sk",
                "V-GEN-rowSort-eq-xs_decimal-numZero1dp-5-sk",
                "V-GEN-rowSort-eq-xs_int-numNegOne-0-sk",
                "V-GEN-rowSort-eq-xs_int-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_int-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_int-numOneMillion-0-sk",
                "V-GEN-rowSort-eq-xs_int-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_int-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_int-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_integer-numNegOne-0-sk",
                "V-GEN-rowSort-eq-xs_integer-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_integer-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_integer-numOneMillion-0-sk",
                "V-GEN-rowSort-eq-xs_integer-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_integer-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_integer-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_long-numNegOne-0-sk",
                "V-GEN-rowSort-eq-xs_long-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_long-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_long-numOneMillion-0-sk",
                "V-GEN-rowSort-eq-xs_long-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_long-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_long-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_negativeInteger-numNegOne-0-sk",
                "V-GEN-rowSort-eq-xs_nonNegativeInteger-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_nonNegativeInteger-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_nonNegativeInteger-numOneMillion-0-sk",
                "V-GEN-rowSort-eq-xs_nonNegativeInteger-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_nonNegativeInteger-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_nonNegativeInteger-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_nonPositiveInteger-numNegOne-0-sk",
                "V-GEN-rowSort-eq-xs_nonPositiveInteger-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_nonPositiveInteger-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_nonPositiveInteger-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_positiveInteger-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_positiveInteger-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_positiveInteger-numOneMillion-0-sk",
                "V-GEN-rowSort-eq-xs_short-numNegOne-0-sk",
                "V-GEN-rowSort-eq-xs_short-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_short-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_short-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_short-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_short-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_time-noon-0-sk",
                "V-GEN-rowSort-eq-xs_token-internalSpace-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedByte-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedByte-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_unsignedByte-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedByte-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_unsignedByte-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_unsignedInt-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedInt-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_unsignedInt-numOneMillion-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedInt-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedInt-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_unsignedInt-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_unsignedLong-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedLong-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_unsignedLong-numOneMillion-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedLong-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedLong-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_unsignedLong-numZero-2-sk",
                "V-GEN-rowSort-eq-xs_unsignedShort-numOne-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedShort-numOne-1-sk",
                "V-GEN-rowSort-eq-xs_unsignedShort-numZero-0-sk",
                "V-GEN-rowSort-eq-xs_unsignedShort-numZero-1-sk",
                "V-GEN-rowSort-eq-xs_unsignedShort-numZero-2-sk",
            )
        },
    }.items()},
    expected_failure_ids=frozenset(f"table-constraints-conformance-{_VERSION}/{s}" for s in [
        "720-tc-report-processor/index-tc-report-table.xml:V-39a",
        "720-tc-report-processor/index-tc-report-table.xml:V-39b",
        "720-tc-report-processor/index-tc-report-table.xml:V-39c",
        "720-tc-report-processor/index-tc-report-table.xml:V-39d",
        "720-tc-report-processor/index-tc-report-table.xml:V-548-10",
        "720-tc-report-processor/index-tc-report-table.xml:V-548-13",
        "720-tc-report-processor/index-tc-report-table.xml:V-548-14",
        "720-tc-report-processor/index-tc-report-table.xml:V-548-17",
        "720-tc-report-processor/index-tc-report-table.xml:V-548-2",
        "720-tc-report-processor/index-tc-report-table.xml:V-548-4",
        "720-tc-report-processor/index-tc-report-table.xml:V-548-5",
        "720-tc-report-processor/index-tc-report-table.xml:V-548-6",
        "720-tc-report-processor/index-tc-report-table.xml:V-548-7",
        "720-tc-report-processor/index-tc-report-table.xml:V-548-9",
        "720-tc-report-processor/index-tc-report-table.xml:V-736-A-lead-crlf-normalizedStringEnum",
        "720-tc-report-processor/index-tc-report-table.xml:V-736-B-trail-crlf-normalizedStringEnum",
        "720-tc-report-processor/index-tc-report-table.xml:V-736-D-mid-crlf-normalizedStringEnum",
        "720-tc-report-processor/index-tc-report-table.xml:V-736p-A-lead-crlf-normalizedStringPattern",
        "720-tc-report-processor/index-tc-report-table.xml:V-736p-B-trail-crlf-normalizedStringPattern",
        "720-tc-report-processor/index-tc-report-table.xml:V-736p-C-trail-crlf-stringPattern",
        "720-tc-report-processor/index-tc-report-table.xml:V-736p-D-mid-crlf-normalizedStringPattern",
        "720-tc-report-processor/index-tc-report-table.xml:V-891-key-tp-over-cp-nomatch",
        "720-tc-report-processor/index-tc-report-table.xml:V-909-comments-invalid-content",
        "720-tc-report-processor/index-tc-report-table.xml:V-909-comments-invalid-partial",
        "720-tc-report-processor/index-tc-report-table.xml:V-909-pref-compound-violate",
        "720-tc-report-processor/index-tc-report-table.xml:V-909-pref-param-to-column-violate",
        "720-tc-report-processor/index-tc-report-table.xml:V-909-pref-param-to-param-violate",
        "720-tc-report-processor/index-tc-report-table.xml:V-909-rk-multi-emptystring",
        "720-tc-report-processor/index-tc-report-table.xml:V-909-rk-multi-violate",
        "720-tc-report-processor/index-tc-report-table.xml:V-909-rk-single-emptystring",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-decimals-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_boolean-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_byte-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_date-tz-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_dateTime-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_dateTime-tz-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_decimal-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_int-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_integer-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_long-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_negativeInteger-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_nonNegativeInteger-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_nonPositiveInteger-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_positiveInteger-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_short-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_time-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_token-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_unsignedByte-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_unsignedInt-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_unsignedLong-nomatch",
        "generated/reference-keys/index-tc-reference-keys.xml:V-GEN-refKey-xs_unsignedShort-nomatch",
    ]),
    info_url="https://www.xbrl.org/Specification/table-constraints/REC-2026-09-10/table-constraints-REC-2026-09-10.html",
    membership_url="https://www.xbrl.org/join",
    name=PurePath(__file__).stem,
)
